project:
  type: website
  output-dir: _site

website:
  title: "UK Statistics RAP"
  site-url: "https://washwalk.github.io/uk-statistics-rap/uk-housing-affordability-monitor/"
  repo-url: "https://github.com/washwalk/uk-statistics-rap"
  navbar: false

format:
  html:
    theme: cosmo
    toc: false
    page-layout: article
    include-in-header: ../site/includes/header-css.html
    include-before-body: ../site/includes/header.html
    css: styles.css

execute:
  echo: false
  warning: false
  message: false
  freeze: false
